# Generated by Django 4.2.21 on 2025-05-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_alter_planuser_unique_together_remove_planuser_plan_and_more'),
        ('user_records', '0002_remove_workoutrecord_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.plan'),
        ),
    ]
