# Generated by Django 4.2.19 on 2025-05-04 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_alter_chatsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
