# Generated by Django 4.2.19 on 2025-05-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('system', 'System'), ('assistant', 'Assistant')], editable=False, max_length=10),
        ),
    ]
