# Generated by Django 4.2.20 on 2025-05-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tool_calls',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('system', 'System'), ('assistant', 'Assistant'), ('tool', 'Tool')], editable=False, max_length=10),
        ),
    ]
