# Generated by Django 4.2.20 on 2025-05-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_tool_calls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='tool_calls',
            field=models.JSONField(default={}),
        ),
    ]
