# Generated by Django 4.2.20 on 2025-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_plan_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutrecord',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
