# Generated by Django 4.2.20 on 2025-05-15 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0005_workoutrecord_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutrecord',
            name='plan',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.planuser'),
        ),
        migrations.AlterField(
            model_name='workoutrecord',
            name='planday',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout.planworkout'),
        ),
        migrations.AlterUniqueTogether(
            name='planuser',
            unique_together={('plan', 'user')},
        ),
    ]
