# Generated by Django 4.2.20 on 2025-05-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_workoutrecord_plan_alter_workoutrecord_planday_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='planuser',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='planuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutrecord',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='workoutrecord',
            name='planday',
        ),
        migrations.RemoveField(
            model_name='workoutrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutrecord',
            name='workout',
        ),
        migrations.DeleteModel(
            name='ExerciseRecord',
        ),
        migrations.DeleteModel(
            name='PlanUser',
        ),
        migrations.DeleteModel(
            name='WorkoutRecord',
        ),
    ]
