# Generated by Django 4.2.20 on 2025-05-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
