# Generated by Django 4.2.20 on 2025-05-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_userinfo_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='frontend_settings',
            field=models.JSONField(default=dict),
        ),
    ]
